[package]
name = "notes_app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "notes_app"

[dependencies]
anchor-lang = "0.31.1"

[features]
idl-build = ["anchor-lang/idl-build"]
